# Generated by Django 5.2.6 on 2025-11-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_detalleventa_litros_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=150)),
                ('evento', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('pk_obj', models.CharField(max_length=50)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('payload', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
