# Generated by Django 5.2.7 on 2025-11-06 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0004_sync_model_changes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producto",
            old_name="precio_por_litro",
            new_name="precio_litro",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="nombre",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="stock",
        ),
        migrations.AddField(
            model_name="cliente",
            name="apellidos",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="cliente",
            name="nombres",
            field=models.CharField(default="", max_length=120),
        ),
        migrations.AddField(
            model_name="producto",
            name="stock_litros",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="detalleventa",
            name="litros",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="producto",
            name="nombre",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="producto",
            name="tipo",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AlterField(
            model_name="venta",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ventas",
                to="tienda.cliente",
            ),
        ),
    ]
